name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: ESLint Lint Check
        run: npm run lint
      - name: ESLint Fix
        run: npm run lint:fix