name: Deploy to NuxtHub
on: push

jobs:
  setup:
    name: "Setup Environment"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - name: Run ESLint
        run: pnpm run lint

  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    needs: [setup, lint]
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: bkozii-2kkm
